### ISSUE TITLE
eiseg要求后缀名pdiparams比原来的多了字母i

### ISSUE THREAD

**Issue by jzp520520** [PaddleCV-SIG/iann#113]
**bug描述**
导入模型文件，软件要求的后缀名pdiparams,比下载的模型文件后缀名多了字母i,后缀名不带i的文件无法访问到，若将不带i的文件后缀改成带i,导入eiseg,则eiseg闪退。python提示：
Traceback (most recent call last):
  File "C:\Users\89755\PycharmProjects\pythonProject\venv\Lib\site-packages\eiseg\app.py", line 56, in run
    success, res = self.controller.setModel(self.param_path, False)
  File "C:\Users\89755\PycharmProjects\pythonProject\venv\Lib\site-packages\eiseg\controller.py", line 103, in setModel
    raise Exception(f"未在 {model_path} 找到模型文件")
Exception: 未在 D:/human_matting-resnet34_vd.pdmodel 找到模型文件

**复现方法**
我们可以如何操作重现这个bug
如：

![image](https://user-images.githubusercontent.com/103249031/165273070-bdac75dc-00bc-41e6-a636-a2607cc96cac.png)

**运行环境（请尽量填写，这可以帮助我们定位问题）：**
 - 系统： Windows10
 - 安装方式：pip
 - 软件版本：eiseg0.5.0  Paddleseg 2.5.0 PaddlePaddle 2.2.2  python 3.9.7

**Comment by geoyee** [comment]
你好。`pdiparams`是静态图模型，现在EISeg需要加载静态图模型，请在这里的地址进行下载

![image](https://user-images.githubusercontent.com/71769312/165276496-308a64fc-9586-40c6-b498-9702f69da4d3.png)
