### ISSUE TITLE
eiseg COCO 格式用于 paddlex、PaddleDetection 训练报错 

### ISSUE THREAD

**Issue by chenglong-do** [PaddleCV-SIG/iann#58]
**bug描述**
使用 EISEG 标注后保存为 COCO 格式，用于paddlex、PaddleDetection 训练时会报错，请问是需要特别转换么？

```
[10/23 17:12:10] ppdet.data.source.coco WARNING: Found an invalid bbox in annotations: im_id: 346, area: 0.0 x1: 664.0, y1: 690.0, x2: 853.0, y2: 908.0.
Traceback (most recent call last):
  File "tools/train.py", line 138, in <module>
    main()
  File "tools/train.py", line 134, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 100, in run
    trainer = Trainer(cfg, mode='train')
  File "/opt/deeplearning/PaddleDetection/ppdet/engine/trainer.py", line 74, in __init__
    self.loader = create('{}Reader'.format(self.mode.capitalize()))(
  File "/opt/deeplearning/PaddleDetection/ppdet/data/reader.py", line 163, in __call__
    self.dataset.parse_dataset()
  File "/opt/deeplearning/PaddleDetection/ppdet/data/source/coco.py", line 243, in parse_dataset
    assert ct > 0, 'not found any coco record in %s' % (anno_path)
AssertionError: not found any coco record in dataset/splotch_coco/train.json
```

**运行环境（请尽量填写，这可以帮助我们定位问题）：**
 - 系统： Linux
 - 安装方式：pip
 - 软件版本：0.3.0.2

**Comment by geoyee** [comment]
@linhandev 韩哥空了看看呢

**Comment by linhandev** [comment]
正在检查这个

**Comment by linhandev** [comment]
您好，请问是直接用的PaddleDetection还是用的PaddleX中的目标检测api？ @chenglong-do

**Comment by chenglong-do** [comment]
> 您好，请问是直接用的PaddleDetection还是用的PaddleX中的目标检测api？ @chenglong-do

您好！两种都有试过，都会报错

**Comment by linhandev** [comment]
收到，之前检测做的少，debug这个可能要点时间

**Comment by linhandev** [comment]
你好，我这边尝试了一下用标注的数据进行paddlex detection的训练，数据读取是正常的。最近我们对coco格式的保存进行了一些完善，建议您这边重新pull代码尝试一下，如果问题还存在的话建议您做一个可以在最新版eiseg上复现这一问题的样例数据集我们定位一下具体的问题在哪。 @chenglong-do

**Comment by ghost** [comment]
你好，我也遇到相同的问题，用的paddlepaddle solov2模型，自己添加了iscrowd后还是会有相同的错误。
macos paddle2.2 pip install eiseg （0.4）

**Comment by ghost** [comment]
已经解决，之前版本bbox和area都没有导致的错误，dev版本生成的coco标注就没有问题了
